import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";

import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import { shadesOfPurple } from "@clerk/themes";
import { Toaster } from "sonner";
import MotionWrapperDelay from "./_components/FramerMotion/MotionWrapperDelay";
import ConvexClientProvider from "./ConvexClientProvider";
import SmokeEffect from "./_components/FramerMotion/SmokeEffect";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Short Video AI Generator",
  description: "Generated by create CodeNow101",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={outfit.className}>
        <div className="animated-bg fixed -z-10 inset-0 opacity-90" />
        <ConvexClientProvider>{children}</ConvexClientProvider>

        <Toaster richColors />
        <MotionWrapperDelay
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.5 }}
          transition={{ duration: 0.9, delay: 0.8 }}
          variants={{
            hidden: { opacity: 0, x: -100 },
            visible: { opacity: 1, x: 0 },
          }}
        >
          <footer className="gradient-background2 py-12 bg-opacity-20">
            {/* <SmokeEffect isVisible={true} /> */}
            <div className="mx-auto px-4 text-center text-gray-300">
              <p>
                © {new Date().getFullYear()} CodeNow101. All Rights Reserved
              </p>
            </div>
          </footer>
        </MotionWrapperDelay>
      </body>
    </html>
  );
}
